### ISSUE TITLE
Error importing polaris on MacOS

### ISSUE THREAD

**Issue by PatWalters** [polaris-hub/polaris#164]
### Polaris version

dev

### Python Version

3.11.3

### Operating System

MacOS

### Installation

mamba install -c conda-forge polaris

### Description

<pre>
>>> import polaris as po
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pwalters/miniconda3/envs/rdkit_2023_05/lib/python3.11/site-packages/polaris/__init__.py", line 7, in <module>
    from .loader import load_benchmark, load_dataset
  File "/Users/pwalters/miniconda3/envs/rdkit_2023_05/lib/python3.11/site-packages/polaris/loader/__init__.py", line 1, in <module>
    from .load import load_benchmark, load_dataset
  File "/Users/pwalters/miniconda3/envs/rdkit_2023_05/lib/python3.11/site-packages/polaris/loader/load.py", line 6, in <module>
    from polaris.benchmark._definitions import (
  File "/Users/pwalters/miniconda3/envs/rdkit_2023_05/lib/python3.11/site-packages/polaris/benchmark/__init__.py", line 1, in <module>
    from polaris.benchmark._base import BenchmarkSpecification
  File "/Users/pwalters/miniconda3/envs/rdkit_2023_05/lib/python3.11/site-packages/polaris/benchmark/_base.py", line 11, in <module>
    from pydantic import (
ImportError: cannot import name 'ValidationInfo' from 'pydantic' (/Users/pwalters/miniconda3/envs/rdkit_2023_05/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)
>>>
</pre>

### Steps to reproduce

import polaris as po

**Comment by PatWalters** [comment]
This may have been a function of the conda environment I was working in.  I created a new conda environment and was able to successfully install polaris-lib.

**Comment by Andrewq11** [comment]
Thanks for submitting this and following up, @PatWalters. I do believe it could be related to the version of `pydantic` you have installed in your `rdkit_2023_05 ` conda environment. Would you mind sharing what that version was?

We should update the `polaris` environment spec to only accept `pydantic` versions which expose the `ValidationInfo` class.

**Comment by PatWalters** [comment]
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydantic
>>> pydantic.__version__
'1.10.13'

**Comment by Andrewq11** [comment]
Thanks! Conda should be throwing an error here about dependency conflicts based on the versioning we already specify for the `polaris` environment. We'll dig into this a bit further and keep this issue open until we have a more concrete explanation.

Thanks for the help!
