### ISSUE TITLE
po.load_benchmark() yields AttributeError  NoneType object has no attribute is_expired

### ISSUE THREAD

**Issue by OleinikovasV** [polaris-hub/polaris#235]
### Polaris version

0.10.1.dev2+gf72ff53

### Python Version

3.12

### Operating System

Mac

### Installation

conda env create -n polaris -f env.yml conda activate polaris  pip install --no-deps -e .

### Description

Installed using the instructions on [github](https://github.com/polaris-hub/polaris?tab=readme-ov-file#setup-dev-environment) - seems to fail client authentication for the demo datasets

### Steps to reproduce

```
import polaris as po
benchmark = po.load_benchmark("polaris/hello-world-benchmark")
```

### Additional output

```
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:25:12) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polaris as po
>>> po.__version__
'0.10.1.dev2+gf72ff53'
>>> benchmark = po.load_benchmark("polaris/hello-world-benchmark")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vladas/Projects/public/polaris/polaris/loader/load.py", line 79, in load_benchmark
    client.ensure_active_token()
  File "/Users/vladas/Projects/public/polaris/polaris/hub/client.py", line 160, in ensure_active_token
    if not (self.has_user_password or self.external_client.ensure_active_token()):
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladas/Projects/public/polaris/polaris/hub/external_client.py", line 87, in ensure_active_token
    return super().ensure_active_token(token) or False
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/polaris/lib/python3.12/site-packages/authlib/oauth2/client.py", line 261, in ensure_active_token
    if not token.is_expired():
           ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_expired'
```

**Comment by OleinikovasV** [comment]
Gets resolved by running this in the shell environment
> polaris login --overwrite

This should be more explicitly documented!
